api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        serialization_context:
            enable_max_depth: true
    collection:
        pagination:
            enabled: false # Désactiver la pagination pour afficher toutes les annonces côté front
    eager_loading:
        max_joins: 5000 # Augmentez la limite
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']