security:
    # Configuration des hashers pour les mots de passe
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Configuration des fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des firewalls
    firewalls:
        # Firewall pour les environnements de développement
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall pour la route de connexion
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password

        # Firewall principal pour protéger les autres routes de l'API
        api:
            pattern: ^/api
            stateless: true
            authenticator:
                - lexik_jwt_authentication.security.jwt_authenticator

    # Contrôles d'accès pour les différentes routes
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
